# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dpct',
                'doc_host': 'https://perceptualrobots.github.io',
                'git_url': 'https://github.com/perceptualrobots/dpct',
                'lib_path': 'dpct'},
  'syms': {'dpct.core': {'dpct.core.foo': ('core.html#foo', 'dpct/core.py')}}}
