# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dpct/',
                'doc_host': 'https://perceptualrobots.github.io',
                'git_url': 'https://github.com/perceptualrobots/dpct/tree/master/',
                'lib_path': 'dpct'},
  'syms': {'dpct.core': {}, 'dpct.funcs': {}}}
