# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://perceptualrobots.github.io/dpct/"

git_url = "https://github.com/perceptualrobots/dpct/tree/master/"

def custom_doc_links(name): return None
=======
# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_hello_func": "01_funcs.ipynb"}

modules = ["core.py",
           "funcs.py"]

doc_url = "https://perceptualrobots.github.io/dpct/"

git_url = "https://github.com/perceptualrobots/dpct/tree/master/"

def custom_doc_links(name): return None
>>>>>>> 0caa89e18af57875d642d601aa96ab73dd676c5b
