# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://perceptualrobots.github.io/dpct/"

git_url = "https://github.com/perceptualrobots/dpct/tree/master/"

def custom_doc_links(name): return None
