# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_funcs.ipynb (unless otherwise specified).

__all__ = ['say_hello_func']

# Cell
def say_hello_func(to):
    "Say hello to somebody"
    return f'Hello {to}!'