name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install nbdev>=2.0.0 jupyter pytest
        pip install -e .
    - name: Check if all notebooks are cleaned and there's no diff between notebooks and library
      run: |
        echo "Check we are starting with clean git checkout"
        if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
        echo "Trying to clean notebooks"
        nbdev_clean
        echo "Check that clean was unnecessary"
        git status -s # display the status to see which nbs need cleaning up
        if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unclean notebooks\n!!!Remember to run nbdev_install_git_hooks"; false; fi
        if [ -n "$(nbdev_export --diff)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi
    - name: Run tests
      run: |
        pytest
